### PR TITLE
KG - Some Refactors Following #867

### PR DESCRIPTION
**Pull request by kayla-glick**

### CODE REVIEW

**Review by jayhardee9 — APPROVED** [review]

**Review by jleonardw9 — APPROVED** [review]

**Review by jwiel86 — APPROVED** [review]

**Comment by jleonardw9** [comment]
I don't see a story in Pivotal for this. Please put one in as a chore with a good description.

**Comment by kayla-glick** [comment]
@jleonardw9 
https://www.pivotaltracker.com/story/show/138151607

**Review by marklohr — APPROVED** [review]

**Comment by Stuart-Johnson** [comment]
Kyle, this seems to fail regularly on travis, when merging with master.

**Comment by jleonardw9** [comment]
@Stuart-Johnson Should we just close this for now? I've tried restarting the build multiple times to no success. He can resubmit once he gets it passing.

**Comment by Stuart-Johnson** [comment]
@jleonardw9 I don't think he saw my comment. I'm pretty sure it's only failing when merged with master, so he needs to merge master into it locally and see what the problem is. I'll let him know.

**Comment by jleonardw9** [comment]
@Stuart-Johnson Ah, ok roger that.

**Pull request closed without merging**
