### PR TITLE
Jl additional details specs

### PR DESCRIPTION
**Pull request by jleonardw9**
Because of the bootstrap modal, the only way I could get the last test (line 38) to work was to use a sleep. Any help getting rid of this would be appreciated.

### CODE REVIEW

**Comment by wtholt** [comment]
@jleonardw9 I tried playing around with different ideas, none of them worked. Sleep is fine with me unless @jayhardee9 has any better ideas.

**Comment by jayhardee9** [comment]
@jleonardw9 Have you tried `expect(page).to have_css('#submissionModal .modal-body form')` in lieu of `sleep 1`? I know it's a little weird to have an expectation there, but it should make Capybara wait for the modal form.

**Review by wtholt — APPROVED** [review]

**Review by jwiel86 — APPROVED** [review]

**Comment by jayhardee9** [comment]
@jleonardw9 Any luck with my suggestion?

**Comment by jleonardw9** [comment]
Sorry, have not tried it yet. I will let you know.

**Comment by jleonardw9** [comment]
Thanks, Jay! That worked and I just made the change.

**Pull request merged**
